# Peuple la base de démonstration avec le catalogue, des comptes de test et des commandes générées.
def remplir_base():
    import sqlite3
    from werkzeug.security import generate_password_hash

    conn = sqlite3.connect("boutique.db")
    conn.execute("PRAGMA foreign_keys = ON;")
    cur = conn.cursor()

    produits = [
    # --- Alimentaire ---
    ("Riz (sac 25kg)", 250000, "Alimentaire", None,
     "Riz blanc alimentaire conditionné en sac de 25 kg, adapté à la préparation des repas et à la consommation familiale."),
    ("Huile végétale (5L)", 85000, "Alimentaire", 75000,
     "Huile végétale alimentaire conditionnée en bidon de 5 litres, adaptée à la cuisson et à la préparation des repas."),
    ("Sucre (1kg)", 12000, "Alimentaire", None,
     "Sucre alimentaire blanc conditionné en paquet de 1 kg, utilisé pour les boissons, desserts et préparations culinaires."),
    ("Farine de blé (1kg)", 9000, "Alimentaire", None,
     "Farine de blé alimentaire conditionnée en paquet de 1 kg, utilisée pour la préparation du pain, des pâtisseries et autres recettes."),
    ("Lait en poudre (400g)", 25000, "Alimentaire", None,
     "Lait en poudre alimentaire conditionné en sachet de 400 g, destiné à la préparation de boissons et recettes à base de lait."),
    ("Pâtes alimentaires (500g)", 8000, "Alimentaire", None,
     "Pâtes alimentaires conditionnées en paquet de 500 g, adaptées à la préparation de repas rapides et familiaux."),
    ("Tomate concentrée (boîte)", 5000, "Alimentaire", None,
     "Tomate concentrée alimentaire conditionnée en boîte, utilisée comme base pour les sauces et différentes préparations culinaires."),
    ("Riz (sac 5kg)", 55000, "Alimentaire", None,
     "Riz blanc alimentaire conditionné en sac de 5 kg, adapté à la préparation des repas et à la consommation familiale."),
    ("Riz parfumé (sac 10kg)", 105000, "Alimentaire", 95000,
     "Riz parfumé alimentaire conditionné en sac de 10 kg, adapté à la préparation des repas et à la consommation familiale."),
    ("Haricot rouge (1kg)", 15000, "Alimentaire", None,
     "Haricot rouge alimentaire conditionné en paquet de 1 kg, utilisé dans la préparation de repas et de plats traditionnels."),
    ("Maïs moulu (1kg)", 7000, "Alimentaire", None,
     "Maïs moulu alimentaire conditionné en paquet de 1 kg, utilisé pour la préparation de repas et de différentes recettes."),
    ("Semoule de blé (1kg)", 10000, "Alimentaire", None,
     "Semoule de blé alimentaire conditionnée en paquet de 1 kg, utilisée pour la préparation de plats, desserts et recettes à base de céréales."),
    ("Oignons (filet 5kg)", 30000, "Alimentaire", None,
     "Oignons frais conditionnés en filet de 5 kg, utilisés comme ingrédient pour les sauces, plats et préparations culinaires."),
    ("Pomme de terre (5kg)", 35000, "Alimentaire", None,
     "Pommes de terre fraîches conditionnées en sac de 5 kg, adaptées à la cuisson, aux fritures et à différentes préparations culinaires."),
    ("Ail (sachet 250g)", 8000, "Alimentaire", None,
     "Ail alimentaire conditionné en sachet de 250 g, utilisé comme condiment pour relever les sauces et plats."),
    ("Piment sec (250g)", 6000, "Alimentaire", None,
     "Piment sec alimentaire conditionné en paquet de 250 g, utilisé comme condiment pour relever les plats et sauces."),
    ("Sel de cuisine (1kg)", 3000, "Alimentaire", None,
     "Sel de cuisine alimentaire conditionné en paquet de 1 kg, utilisé pour assaisonner et préparer les repas."),
    ("Cube Maggi (paquet)", 4000, "Alimentaire", None,
     "Cube d'assaisonnement alimentaire conditionné en paquet, utilisé pour relever les sauces, soupes et plats."),
    ("Vinaigre (500ml)", 6000, "Alimentaire", None,
     "Vinaigre alimentaire conditionné en bouteille de 500 ml, utilisé pour l'assaisonnement, les sauces et diverses préparations culinaires."),
    ("Mayonnaise (400g)", 18000, "Alimentaire", 15000,
     "Mayonnaise alimentaire conditionnée en pot de 400 g, utilisée comme sauce et accompagnement pour les repas."),
    ("Sardines en boîte", 7000, "Alimentaire", None,
     "Sardines alimentaires conservées en boîte, prêtes à consommer et adaptées à la préparation de repas."),
    ("Thon en boîte", 12000, "Alimentaire", None,
     "Thon alimentaire conservé en boîte, prêt à consommer et adapté aux salades, sandwichs et préparations culinaires."),
    ("Corned-beef (boîte)", 15000, "Alimentaire", None,
     "Corned-beef alimentaire conservé en boîte, utilisé pour la préparation de repas et plats rapides."),
    ("Biscuits (paquet)", 5000, "Alimentaire", None,
     "Biscuits alimentaires conditionnés en paquet, adaptés au goûter, aux collations et à la consommation quotidienne."),
    ("Chocolat en poudre (400g)", 22000, "Alimentaire", None,
     "Chocolat en poudre alimentaire conditionné en paquet de 400 g, utilisé pour préparer des boissons chocolatées et des desserts."),
    ("Confiture (400g)", 17000, "Alimentaire", None,
     "Confiture alimentaire conditionnée en pot de 400 g, utilisée pour accompagner le pain, les tartines et les desserts."),
    ("Beurre (250g)", 20000, "Alimentaire", None,
     "Beurre alimentaire conditionné en paquet de 250 g, utilisé pour la cuisson, les tartines, la pâtisserie et différentes recettes."),
    ("Œufs (plateau de 30)", 45000, "Alimentaire", 40000,
     "Œufs alimentaires conditionnés en plateau de 30 unités, utilisés pour la cuisson, la pâtisserie et la préparation de repas."),
    ("Pain de mie", 10000, "Alimentaire", None,
     "Pain de mie alimentaire, adapté à la préparation de sandwichs, tartines et repas rapides."),
    ("Miel naturel (500ml)", 35000, "Alimentaire", None,
     "Miel naturel alimentaire conditionné en bouteille de 500 ml, utilisé pour sucrer les boissons, accompagner les aliments et préparer des recettes."),

    # --- Hygiène ---
    ("Savon de Marseille", 3000, "Hygiène", None,
     "Savon de Marseille destiné à l'hygiène corporelle et au nettoyage, adapté à un usage quotidien."),
    ("Dentifrice", 15000, "Hygiène", None,
     "Dentifrice destiné à l'hygiène bucco-dentaire, utilisé pour nettoyer les dents et maintenir une bonne hygiène quotidienne."),
    ("Shampoing (250ml)", 22000, "Hygiène", None,
     "Shampoing conditionné en flacon de 250 ml, destiné au lavage et à l'hygiène des cheveux."),
    ("Papier hygiénique (pack 4)", 18000, "Hygiène", None,
     "Papier hygiénique conditionné en pack de 4 rouleaux, destiné à l'hygiène quotidienne."),
    ("Gel douche (500ml)", 30000, "Hygiène", 25000,
     "Gel douche conditionné en flacon de 500 ml, destiné au nettoyage et à l'hygiène quotidienne du corps."),
    ("Brosse à dents (unité)", 6000, "Hygiène", None,
     "Brosse à dents vendue à l'unité, destinée au nettoyage quotidien des dents et à l'hygiène bucco-dentaire."),
    ("Coton-tiges (paquet)", 5000, "Hygiène", None,
     "Coton-tiges conditionnés en paquet, destinés aux soins et à l'hygiène personnelle."),
    ("Serviettes hygiéniques (paquet)", 12000, "Hygiène", None,
     "Serviettes hygiéniques conditionnées en paquet, destinées à l'hygiène féminine pendant les menstruations."),
    ("Couches bébé (paquet)", 45000, "Hygiène", 38000,
     "Couches pour bébé conditionnées en paquet, destinées à l'hygiène et au confort des nourrissons."),
    ("Déodorant roll-on", 20000, "Hygiène", None,
     "Déodorant roll-on destiné à l'hygiène corporelle quotidienne et à la réduction des odeurs de transpiration."),
    ("Crème hydratante (200ml)", 28000, "Hygiène", None,
     "Crème hydratante conditionnée en flacon de 200 ml, destinée à hydrater et protéger la peau."),
    ("Rasoir jetable (lot de 3)", 9000, "Hygiène", None,
     "Rasoirs jetables conditionnés en lot de 3, destinés au rasage et à l'entretien de la pilosité."),
    ("Mousse à raser", 18000, "Hygiène", None,
     "Mousse à raser destinée à faciliter le rasage et à protéger la peau pendant l'utilisation du rasoir."),
    ("Savon liquide pour mains (500ml)", 15000, "Hygiène", None,
     "Savon liquide pour les mains conditionné en flacon de 500 ml, destiné au lavage et à l'hygiène quotidienne des mains."),
    ("Lingettes bébé (paquet)", 16000, "Hygiène", None,
     "Lingettes pour bébé conditionnées en paquet, destinées au nettoyage et à l'hygiène quotidienne des nourrissons."),
    ("Talc pour bébé", 10000, "Hygiène", None,
     "Talc pour bébé destiné aux soins de la peau et à l'hygiène quotidienne des nourrissons."),
    ("Bain moussant (500ml)", 24000, "Hygiène", None,
     "Bain moussant conditionné en flacon de 500 ml, destiné à l'hygiène corporelle et au nettoyage du corps."),
    ("Cure-dents (boîte)", 2000, "Hygiène", None,
     "Cure-dents conditionnés en boîte, destinés à l'hygiène bucco-dentaire et au nettoyage entre les dents."),

    # --- Papeterie ---
    ("Cahier 100 pages", 5000, "Papeterie", None,
     "Cahier de papeterie de 100 pages, destiné à la prise de notes, aux exercices scolaires et à l'écriture quotidienne."),
    ("Stylo bic (unité)", 1500, "Papeterie", None,
     "Stylo bille vendu à l'unité, destiné à l'écriture quotidienne, aux études et à la prise de notes."),
    ("Crayon à papier (unité)", 1000, "Papeterie", None,
     "Crayon à papier vendu à l'unité, destiné au dessin, à l'écriture et aux travaux scolaires."),
    ("Gomme", 1500, "Papeterie", None,
     "Gomme de papeterie destinée à effacer les traces de crayon et utilisée pour les travaux scolaires et d'écriture."),
    ("Taille-crayon", 2000, "Papeterie", None,
     "Taille-crayon de papeterie destiné à tailler les crayons et adapté à un usage scolaire et quotidien."),
    ("Règle 30cm", 2500, "Papeterie", None,
     "Règle de 30 cm destinée au traçage, à la mesure et aux travaux scolaires et de dessin."),
    ("Classeur A4", 12000, "Papeterie", None,
     "Classeur au format A4 destiné au rangement, à l'organisation et à la conservation de documents et feuilles."),
    ("Feuilles A4 (rame 500)", 35000, "Papeterie", 30000,
     "Rame de 500 feuilles au format A4, destinée à l'impression, à l'écriture, aux documents scolaires et administratifs."),
    ("Surligneur (lot de 4)", 8000, "Papeterie", None,
     "Lot de 4 surligneurs destiné à mettre en évidence des informations importantes dans les documents et notes."),
    ("Colle en bâton", 3000, "Papeterie", None,
     "Colle en bâton destinée aux travaux manuels, scolaires et à l'assemblage de feuilles et documents."),
    ("Ciseaux", 5000, "Papeterie", None,
     "Ciseaux de papeterie destinés à découper du papier, du carton et différents matériaux légers."),
    ("Agrafeuse", 15000, "Papeterie", None,
     "Agrafeuse de papeterie destinée à assembler et fixer plusieurs feuilles de papier."),
    ("Agrafes (boîte)", 2000, "Papeterie", None,
     "Boîte d'agrafes destinée à alimenter une agrafeuse et à assembler des documents papier."),
    ("Calculatrice scientifique", 65000, "Papeterie", 55000,
     "Calculatrice scientifique destinée aux calculs mathématiques, scientifiques et scolaires."),
    ("Sac à dos scolaire", 90000, "Papeterie", None,
     "Sac à dos scolaire destiné au transport de cahiers, livres, fournitures et matériel scolaire."),
    ("Trousse", 12000, "Papeterie", None,
     "Trousse de papeterie destinée au rangement et au transport des stylos, crayons, gommes et autres fournitures."),
    ("Marqueur permanent (lot de 3)", 9000, "Papeterie", None,
     "Lot de 3 marqueurs permanents destinés à écrire ou identifier durablement différents supports."),
    ("Cahier de brouillon", 3000, "Papeterie", None,
     "Cahier de brouillon destiné aux notes temporaires, exercices, calculs et travaux scolaires."),

    # --- Électronique ---
    ("Clé USB 32GB", 45000, "Électronique", None,
     "Clé USB de 32 Go destinée au stockage, au transfert et au transport de fichiers numériques."),
    ("Ampoule LED", 12000, "Électronique", None,
     "Ampoule LED destinée à l'éclairage des pièces et espaces intérieurs avec une faible consommation électrique."),
    ("Pile AA (paquet de 4)", 10000, "Électronique", None,
     "Paquet de 4 piles AA destiné à alimenter différents appareils électroniques et électriques compatibles."),
    ("Chargeur téléphone (câble USB-C)", 25000, "Électronique", None,
     "Chargeur de téléphone avec câble USB-C destiné à recharger les smartphones et appareils compatibles USB-C."),
    ("Écouteurs filaires", 20000, "Électronique", None,
     "Écouteurs filaires destinés à écouter de la musique, des appels et du contenu audio sur des appareils compatibles."),
    ("Écouteurs Bluetooth", 120000, "Électronique", 99000,
     "Écouteurs Bluetooth sans fil destinés à écouter de la musique et passer des appels avec des appareils compatibles."),
    ("Powerbank 10000mAh", 150000, "Électronique", 130000,
     "Batterie externe de 10000 mAh destinée à recharger les smartphones et autres appareils électroniques mobiles."),
    ("Rallonge électrique (5m)", 35000, "Électronique", None,
     "Rallonge électrique de 5 mètres destinée à étendre la portée d'une prise électrique pour alimenter différents appareils."),
    ("Multiprise 4 prises", 40000, "Électronique", None,
     "Multiprise électrique avec 4 prises destinée à connecter plusieurs appareils électriques à une même source d'alimentation."),
    ("Lampe torche LED", 18000, "Électronique", None,
     "Lampe torche LED destinée à fournir un éclairage portable pour les déplacements et les espaces sombres."),
    ("Radio portable", 55000, "Électronique", None,
     "Radio portable destinée à écouter des émissions et contenus audio à différents endroits."),
    ("Câble HDMI (2m)", 30000, "Électronique", None,
     "Câble HDMI de 2 mètres destiné à transmettre des signaux audio et vidéo entre appareils compatibles."),
    ("Souris USB", 35000, "Électronique", None,
     "Souris USB destinée au contrôle et à la navigation sur un ordinateur compatible."),
    ("Clavier USB", 60000, "Électronique", None,
     "Clavier USB destiné à la saisie de texte, aux commandes et à l'utilisation quotidienne d'un ordinateur."),
    ("Casque audio filaire", 45000, "Électronique", None,
     "Casque audio filaire destiné à écouter de la musique, des vidéos et des contenus audio sur des appareils compatibles."),
    ("Ventilateur de bureau USB", 50000, "Électronique", None,
     "Ventilateur de bureau USB destiné à fournir une ventilation personnelle et à rafraîchir un espace de travail."),
    ("Adaptateur secteur universel", 28000, "Électronique", None,
     "Adaptateur secteur universel destiné à alimenter différents appareils électriques et électroniques compatibles."),
    ("Batterie rechargeable AA (lot de 4)", 25000, "Électronique", None,
     "Lot de 4 batteries rechargeables AA destiné à alimenter des appareils électroniques compatibles et à être réutilisé après recharge."),

    # --- Boisson ---
    ("Eau minérale (1.5L)", 5000, "Boisson", None,
     "Eau minérale conditionnée en bouteille de 1,5 litre, destinée à la consommation quotidienne et à l'hydratation."),
    ("Jus de fruit (1L)", 15000, "Boisson", None,
     "Jus de fruit conditionné en bouteille de 1 litre, destiné à la consommation et à accompagner les repas ou collations."),
    ("Café soluble (100g)", 20000, "Boisson", None,
     "Café soluble conditionné en paquet de 100 g, destiné à la préparation rapide de boissons chaudes."),
    ("Thé vert (boîte 25 sachets)", 12000, "Boisson", None,
     "Thé vert conditionné en boîte de 25 sachets, destiné à la préparation de boissons chaudes."),
    ("Boisson gazeuse (1.5L)", 10000, "Boisson", None,
     "Boisson gazeuse conditionnée en bouteille de 1,5 litre, destinée à la consommation et à accompagner les repas."),
    ("Boisson gazeuse (canette 33cl)", 4000, "Boisson", None,
     "Boisson gazeuse conditionnée en canette de 33 cl, destinée à la consommation individuelle et aux collations."),
    ("Jus d'orange (1L)", 16000, "Boisson", None,
     "Jus d'orange conditionné en bouteille de 1 litre, destiné à la consommation et à accompagner les repas ou collations."),
    ("Eau minérale (pack 6x1.5L)", 27000, "Boisson", 24000,
     "Pack de 6 bouteilles d'eau minérale de 1,5 litre, destiné à l'hydratation et à la consommation familiale."),
    ("Sirop de fruit (750ml)", 18000, "Boisson", None,
     "Sirop de fruit conditionné en bouteille de 750 ml, destiné à préparer des boissons fruitées et rafraîchissantes."),
    ("Lait concentré sucré", 9000, "Boisson", None,
     "Lait concentré sucré destiné à la préparation de boissons, desserts et recettes nécessitant du lait sucré."),
    ("Yaourt à boire (1L)", 14000, "Boisson", None,
     "Yaourt à boire conditionné en bouteille de 1 litre, destiné à la consommation comme boisson et collation."),
    ("Bissap (jus local, 1L)", 10000, "Boisson", None,
     "Jus de bissap local conditionné en bouteille de 1 litre, destiné à la consommation et au rafraîchissement."),
    ("Gingembre (jus local, 1L)", 11000, "Boisson", None,
     "Jus de gingembre local conditionné en bouteille de 1 litre, destiné à la consommation et au rafraîchissement."),
    ("Café moulu (250g)", 25000, "Boisson", None,
     "Café moulu conditionné en paquet de 250 g, destiné à la préparation de boissons chaudes."),
    ("Boisson énergisante (canette)", 8000, "Boisson", None,
     "Boisson énergisante conditionnée en canette, destinée à la consommation lors d'activités nécessitant une sensation de dynamisme."),
    ("Nescafé 3 en 1 (boîte 10 sticks)", 15000, "Boisson", None,
     "Boisson instantanée au café conditionnée en boîte de 10 sticks, destinée à préparer rapidement des boissons chaudes.")
    ]

    cur.executemany(
        "INSERT INTO produits (nom, prix, type_prod, prix_promo,descrip) VALUES (?, ?, ?, ?, ?)",
        produits
    )

    conn.commit()
    print(f"{len(produits)} produits insérés.")

    clients_bruts = [
        ("Bah", "Ibrahima Sory", "Ratoma, Conakry", "ibrahimasorybh63@gmail.com"),
        ("Bah", "Fatoumata", "Kaloum, Conakry", "fatoumata.bah@mail.com"),
        ("Camara", "Mohamed", "Kindia", "mohamed.camara@mail.com"),
        ("Barry", "Aissatou", "Dixinn, Conakry", "aissatou.barry@mail.com"),
        ("Sylla", "Mamadou", "Kankan", "mamadou.sylla@mail.com"),
        ("Conde", "Hadja Djénabou", "Matam, Conakry", "hadja.conde@mail.com"),
        ("Toure", "Alpha Oumar", "Labé", "alpha.toure@mail.com"),
        ("Keita", "Mariama", "Ratoma, Conakry", "mariama.keita@mail.com"),
        ("Sow", "Ousmane", "Nzérékoré", "ousmane.sow@mail.com"),
        ("Cissé", "Kadiatou", "Kaloum, Conakry", "kadiatou.cisse@mail.com"),
        ("Bangoura", "Sékou", "Boké", "sekou.bangoura@mail.com"),
        ("Fofana", "Aminata", "Kissidougou", "aminata.fofana@mail.com"),
        ("Diakite", "Lansana", "Ratoma, Conakry", "lansana.diakite@mail.com"),
        ("Soumah", "Binta", "Coyah", "binta.soumah@mail.com"),
        ("Kourouma", "Alseny", "Faranah", "alseny.kourouma@mail.com"),
    ]

    # Mot de passe de test unique pour tous les clients de seed : "test1234"
    mdp_hash_test = generate_password_hash("test1234")

    clients = [
        (nom, prenom, adresse, email, mdp_hash_test)
        for (nom, prenom, adresse, email) in clients_bruts
    ]

    cur.executemany(
        "INSERT INTO clients (nom, prenom, adresse, email, mdp_hash) VALUES (?, ?, ?, ?, ?)",
        clients
    )

    conn.commit()
    print(f"{len(clients)} clients insérés.")
    from generer_comm import generer_commandes
    generer_commandes(conn)
    conn.close()    
